# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
tmuximum_path = "[[ ! $PATH =~ {{ dir }} ]] && export PATH=\"$PATH:{{ dir }}\"\n"
# tmuximum_source = "{% for file in files %}chmod +x \"{{ file }}\" \n source \"{{ file }}\"\n{% endfor %}"
tmuximum_source = "chmod +x {{ dir }}/tmuximum \n source {{ dir }}/tmuximum\n"

[plugins]
[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.tmuximum]
github = 'arks22/tmuximum'
apply = ['tmuximum_path', 'tmuximum_source']

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'

[plugins.dotfiles-defers]
local = "~/.config/zsh/"
use = ["{!00-sync,*}.zsh"]

[plugins.dotfiles-sync]
local = "~/.config/zsh"
use = ["00-sync.zsh"]
apply = ["source"]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
