[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # ステータスバー
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {'colorscheme': 'wombat'}
'''

[[plugins]] # deniteに必要
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # deniteに必要
repo = 'Shougo/neomru.vim'

[[plugins]] # tomlを表示
repo  = 'cespare/vim-toml'

[[plugins]] # color scheme
repo = 'jacoborus/tender'
hook_add = '''
  colorscheme tender
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  " au MyAutoCmd VimEnter * nested colorscheme tender
'''

[[plugins]] # easymotion
repo = 'easymotion/vim-easymotion'

[[plugins]] # denite
repo = 'Shougo/denite.nvim'
hook_add = '''
    "ESCキーでdeniteを終了
    "call denite#custom#map('insert', '<esc>', '<denite:enter_mode:normal>', 'noremap')
    "call denite#custom#map('normal', '<esc>', '<denite:quit>', 'noremap')

    " file/recの除外ファイル設定
    call denite#custom#source('file/rec', 'matchers', ['matcher_fuzzy','matcher_ignore_globs'])
    call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
      \ [
      \ '.git/', 'build/', '__pycache__/', 'node_modules/', '.mypy_cache/', '.venv/',
      \ 'images/', '*.o', '*.make',
      \ '*.min.*',
      \ 'img/', 'fonts/', 'tmp/'])

    "バッファと最近使ったファイル
    noremap <C-B> :DeniteProjectDir -start-filter buffer file_mru<CR>
    inoremap <C-B> <ESC>:DeniteProjectDir -start-filter buffer file_mru<CR>

    "バッファとプロジェクト内のファイル
    noremap <C-P> :DeniteProjectDir -start-filter buffer file/rec<CR>

    "バッファ一覧
    noremap <Leader>ub :Denite buffer<CR>

    "最近使ったファイルの一覧
    noremap <Leader>um :Denite file_mru<CR>

    "カレントディレクトリ
    noremap <Leader>uf :DeniteBufferDir file/rec<CR>

    "バッファ一覧
    autocmd FileType denite call s:denite_my_settings()
    function! s:denite_my_settings() abort
      nnoremap <silent><buffer><expr> <CR>
      \ denite#do_map('do_action')
      nnoremap <silent><buffer><expr> p
      \ denite#do_map('do_action', 'preview')
      nnoremap <silent><buffer><expr> <esc>
      \ denite#do_map('quit')
      nnoremap <silent><buffer><expr> i
      \ denite#do_map('open_filter_buffer')
      nnoremap <silent><buffer><expr> <Space>
      \ denite#do_map('toggle_select').'j'
    endfunction

'''

[[plugins]] # NerdTree
repo = 'scrooloose/nerdtree'
hook_add = '''
    noremap nt :NERDTreeToggle<CR>
    let file_name = expand("%")
	let NERDTreeShowHidden = 1
    let g:NERDTreeWinSize=26
    "if has('vim_starting') &&  file_name == ""
    "    autocmd VimEnter * NERDTree ./
    "endif
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]] # Indent Guides
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_start_level = 2
    let g:indent_guides_guide_size = 1
    let g:indent_guides_auto_colors=0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=234
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=236
'''

#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'
#rev = 'next'
#build = 'bash install.sh'
#hook_add = '''
#    let g:LanguageClient_serverCommands = {
#        \ 'python': ['pyls'],
#    \ }
#    let g:LanguageClient_useVirtualText = 0
#    augroup LanguageClient_config
#        autocmd!
#        autocmd User LanguageClientStarted setlocal signcolumn=yes
#        autocmd User LanguageClientStopped setlocal signcolumn=auto
#    augroup END
#'''

[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0
rev = "release"
hook_add = """
    set statusline^=%{coc#status()}
    let g:coc_global_extensions = [
      \ 'coc-jedi',
      \ 'coc-json',
      \ 'coc-tabnine',
      \ ]

      inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
    inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

    function! s:check_back_space() abort
      let col = col('.') - 1
      return !col || getline('.')[col - 1]  =~# '\s'
    endfunction

    inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

"""

[[plugins]] # perl風正規表現
repo = 'othree/eregex.vim'

